// Shared Persian microcopy for the admin. Views import STR from here so the
// same words appear everywhere (buttons, states, errors, confirmations).
// Persian digits in prose; functions take a count/name and return a sentence.

const fa = s => String(s ?? '').replace(/[0-9]/g, d => '۰۱۲۳۴۵۶۷۸۹'[d]);

export const STR = {
  app: {
    name: 'پنل مدیریت SysaiQ',
    brand: 'SysaiQ',
    brandSub: 'پنل مدیریت',
    viewSite: 'مشاهدهٔ سایت',
    legacyPanel: 'پنل قدیمی',
    menu: 'منو',
    search: 'جستجو و پرش',
    searchHint: 'نام صفحه را بنویسید…',
    noResults: 'چیزی پیدا نشد',
    skip: 'پرش به محتوا',
    dirtyCounter: n => (n === 1 ? 'یک تغییر ذخیره‌نشده' : `${fa(n)} تغییر ذخیره‌نشده`),
  },

  actions: {
    save: 'ذخیره',
    saveAndPublish: 'ذخیره و انتشار',
    saving: 'در حال ذخیره…',
    cancel: 'انصراف',
    close: 'بستن',
    delete: 'حذف',
    remove: 'حذف',
    edit: 'ویرایش',
    add: 'افزودن',
    create: 'ایجاد',
    new: 'جدید',
    confirm: 'تأیید',
    back: 'بازگشت',
    retry: 'تلاش دوباره',
    refresh: 'به‌روزرسانی',
    search: 'جستجو',
    clear: 'پاک‌کردن',
    upload: 'بارگذاری تصویر',
    replace: 'جایگزینی',
    moveUp: 'انتقال به بالا',
    moveDown: 'انتقال به پایین',
    copy: 'کپی',
    copied: 'کپی شد',
    show: 'نمایش',
    hide: 'پنهان‌کردن',
    view: 'مشاهده',
    open: 'بازکردن',
    more: 'بیشتر',
    apply: 'اعمال',
    reset: 'بازنشانی',
    test: 'آزمایش',
    logout: 'خروج',
    login: 'ورود',
    yes: 'بله',
    no: 'خیر',
    discard: 'دور انداختن تغییرات',
    stay: 'ماندن در صفحه',
    select: 'انتخاب…',
  },

  states: {
    loading: 'در حال بارگذاری…',
    saved: 'ذخیره شد',
    created: 'ایجاد شد',
    deleted: 'حذف شد',
    updated: 'به‌روز شد',
    uploaded: 'تصویر بارگذاری شد — فراموش نکنید ذخیره کنید',
    empty: 'هنوز چیزی ثبت نشده است',
    emptyHint: 'اولین مورد را با دکمهٔ «افزودن» بسازید.',
    noMatch: 'موردی با این فیلتر پیدا نشد',
    noMatchHint: 'عبارت جستجو یا فیلترها را تغییر دهید.',
    error: 'مشکلی پیش آمد',
    errorHint: 'اتصال را بررسی کنید و دوباره تلاش کنید.',
    unsaved: 'تغییرات ذخیره‌نشده دارید',
    allSaved: 'همهٔ تغییرات ذخیره شده است',
    comingSoon: 'به‌زودی',
    comingSoonHint: 'این بخش در حال ساخت است. تا آماده‌شدن آن می‌توانید از پنل قدیمی استفاده کنید.',
    notConfigured: 'تنظیم نشده',
    configured: 'تنظیم شده',
    published: 'منتشرشده',
    draft: 'پیش‌نویس',
    enabled: 'فعال',
    disabled: 'غیرفعال',
    on: 'روشن',
    off: 'خاموش',
    yes: 'بله',
    no: 'خیر',
    none: '—',
    items: n => (n === 0 ? 'بدون مورد' : `${fa(n)} مورد`),
    of: (a, b) => `${fa(a)} از ${fa(b)}`,
    count: n => fa(n),
  },

  errors: {
    network: 'ارتباط با سرور برقرار نشد. اتصال اینترنت را بررسی کنید.',
    unauthorized: 'نشست شما به پایان رسیده است. دوباره وارد شوید.',
    csrf: 'درخواست از مبدأ نامعتبر رد شد. صفحه را تازه‌سازی کنید.',
    forbidden: 'اجازهٔ انجام این کار را ندارید.',
    notFound: 'مورد درخواستی پیدا نشد.',
    validation: 'برخی فیلدها نیاز به اصلاح دارند.',
    rateLimited: 'تعداد تلاش‌ها بیش از حد مجاز است. چند دقیقه صبر کنید.',
    tooLarge: 'حجم داده بیش از حد مجاز است.',
    server: 'خطای داخلی سرور. کمی بعد دوباره تلاش کنید.',
    unknown: 'خطای ناشناخته.',
    unsupportedImage: 'فقط تصاویر JPEG، PNG، WebP و GIF پذیرفته می‌شوند.',
    fileTooLarge: 'حجم فایل بیش از ۸ مگابایت است.',
    uploadFailed: 'بارگذاری انجام نشد.',
    viewLoad: 'این صفحه بارگذاری نشد.',
    clipboard: 'کپی در حافظه ممکن نبود.',
  },

  fields: {
    required: 'این فیلد الزامی است',
    invalid: 'مقدار نامعتبر است',
    minLength: n => `حداقل ${fa(n)} نویسه`,
    maxLength: n => `حداکثر ${fa(n)} نویسه`,
    min: n => `حداقل ${fa(n)}`,
    max: n => `حداکثر ${fa(n)}`,
    number: 'فقط عدد وارد کنید',
    integer: 'فقط عدد صحیح',
    email: 'نشانی ایمیل معتبر نیست',
    mobile: 'شمارهٔ موبایل معتبر نیست (مثال: ۰۹۱۲۱۲۳۴۵۶۷)',
    slug: 'فقط حروف لاتین کوچک، ارقام و خط تیره',
    slugTaken: 'این نامک قبلاً استفاده شده است',
    url: 'نشانی معتبر نیست',
    https: 'نشانی باید با https شروع شود',
    date: 'تاریخ معتبر نیست',
    mismatch: 'مقادیر یکسان نیستند',
    json: 'JSON معتبر نیست',
    charCount: (n, max) => `${fa(n)} / ${fa(max)}`,
    optional: 'اختیاری',
    faLabel: 'فارسی',
    enLabel: 'English',
    keepCurrent: 'برای حفظ مقدار فعلی خالی بگذارید',
    addTag: 'برچسب را بنویسید و Enter بزنید',
    slugPreview: 'نشانی صفحه',
    autoSlug: 'به‌طور خودکار از عنوان انگلیسی ساخته می‌شود',
    chooseImage: 'انتخاب تصویر',
    imageUrl: 'نشانی تصویر',
    noImage: 'بدون تصویر',
    today: 'امروز',
    clearDate: 'پاک‌کردن',
    prevMonth: 'ماه قبل',
    nextMonth: 'ماه بعد',
  },

  confirm: {
    deleteTitle: 'حذف شود؟',
    deleteMessage: name => (name ? `«${name}» برای همیشه حذف می‌شود. این کار قابل بازگشت نیست.` : 'این مورد برای همیشه حذف می‌شود. این کار قابل بازگشت نیست.'),
    deleteConfirm: 'بله، حذف شود',
    leaveTitle: 'تغییرات ذخیره نشده‌اند',
    leaveMessage: 'اگر این صفحه را ترک کنید، تغییرات ذخیره‌نشده از بین می‌روند.',
    leaveConfirm: 'ترک صفحه',
    logoutTitle: 'خروج از پنل',
    logoutMessage: 'از پنل مدیریت خارج می‌شوید.',
  },

  auth: {
    title: 'ورود به پنل مدیریت',
    subtitle: 'برای ادامه، نام کاربری و رمز عبور خود را وارد کنید.',
    username: 'نام کاربری',
    password: 'رمز عبور',
    signIn: 'ورود',
    signingIn: 'در حال ورود…',
    invalid: 'نام کاربری یا رمز عبور درست نیست.',
    tooMany: 'تلاش‌های ناموفق زیاد بوده است. ۱۵ دقیقه صبر کنید و دوباره امتحان کنید.',
    expired: 'نشست شما به پایان رسیده است. برای ادامه دوباره وارد شوید؛ تغییرات صفحه حفظ می‌شود.',
    showPassword: 'نمایش رمز عبور',
    hidePassword: 'پنهان‌کردن رمز عبور',
    welcome: name => `خوش آمدید${name ? `، ${name}` : ''}`,
    loggedOut: 'با موفقیت خارج شدید.',
    footer: 'دسترسی فقط برای مدیر سایت. این صفحه در موتورهای جستجو نمایه نمی‌شود.',
  },

  nav: {
    dashboard: 'داشبورد',
    groups: {
      content: 'محتوا',
      customers: 'مشتریان',
      finance: 'مالی',
      trust: 'هویت و اعتماد',
      ai: 'هوش مصنوعی',
      settings: 'تنظیمات',
    },
  },

  dashboard: {
    title: 'داشبورد',
    subtitle: 'نمای کلی سایت و کارهایی که هنوز مانده‌اند.',
    leads: 'سرنخ‌ها',
    newLeads: 'سرنخ جدید',
    conversationsToday: 'گفت‌وگوی امروز',
    projects: 'پروژه‌ها',
    faqs: 'سؤالات متداول',
    knowledge: 'مدخل‌های پایگاه دانش',
    setupTitle: 'راه‌اندازی سایت',
    setupHint: 'برای انتشار کامل سایت، این موارد باید تکمیل شوند.',
    setupDone: 'همهٔ موارد راه‌اندازی تکمیل شده است.',
    system: 'وضعیت سیستم',
    node: 'نسخهٔ Node',
    schema: 'نسخهٔ پایگاه داده',
    uptime: 'مدت روشن‌بودن',
    env: 'محیط اجرا',
    purgeCache: 'پاک‌کردن کش',
    cachePurged: 'کش پاک شد',
    setup: {
      openai_key: { label: 'کلید OpenAI دستیار', hint: 'بدون کلید، دستیار هوشمند پاسخ نمی‌دهد.', href: '#/ai' },
      default_password_suspected: { label: 'تغییر رمز پیش‌فرض مدیر', hint: 'رمز اولیه هنوز عوض نشده است.', href: '#/account', invert: true },
      // no admin screen for SMTP: SMTP_HOST/USER/PASS live only in the server's .env
      smtp: { label: 'تنظیم ایمیل (SMTP)', hint: 'اعلان سرنخ‌های جدید با ایمیل ارسال می‌شود. این تنظیم در فایل .env سرور انجام می‌شود و از پنل قابل تغییر نیست.', href: null },
      backup_recent: { label: 'پشتیبان‌گیری اخیر', hint: 'نسخهٔ پشتیبان پایگاه داده در ۲۴ ساعت گذشته.', href: '#/backup' },
      site_info: { label: 'اطلاعات تماس و هویت', hint: 'نشانی، تلفن و ایمیل که در همهٔ صفحات استفاده می‌شود.', href: '#/site-info' },
      // «تماس» is not a page row (migration 012): /contact is rendered from «اطلاعات تماس»
      required_pages: { label: 'صفحات الزامی', hint: 'دربارهٔ ما، قوانین، حریم خصوصی و بازپرداخت.', href: '#/pages' },
      enamad: { label: 'نماد اعتماد (اینماد)', hint: 'کد نماد را در بخش اینماد و نمادها ثبت کنید.', href: '#/trust' },
      gateway: { label: 'درگاه پرداخت', hint: 'برای لینک پرداخت فاکتورها لازم است.', href: '#/gateways' },
      sms: { label: 'پنل پیامک', hint: 'برای اعلان و پیگیری سرنخ‌ها.', href: '#/sms' },
    },
  },

  account: {
    title: 'حساب و امنیت',
    subtitle: 'رمز عبور و نشست‌های ورود.',
    username: 'نام کاربری',
    lastLogin: 'آخرین ورود',
    pwdChanged: 'آخرین تغییر رمز',
    never: 'هرگز',
    defaultWarn: 'رمز عبور اولیه هنوز تغییر نکرده است. همین حالا یک رمز جدید انتخاب کنید.',
    changePassword: 'تغییر رمز عبور',
    current: 'رمز عبور فعلی',
    next: 'رمز عبور جدید',
    confirm: 'تکرار رمز عبور جدید',
    rule: 'حداقل ۱۰ نویسه، شامل حداقل یک حرف و یک رقم.',
    changed: 'رمز عبور تغییر کرد. نشست‌های دیگر بسته شدند.',
    wrongCurrent: 'رمز عبور فعلی درست نیست.',
    sameAsCurrent: 'رمز جدید باید با رمز فعلی متفاوت باشد.',
    logoutAll: 'خروج از همهٔ دستگاه‌ها',
    logoutAllHint: 'همهٔ نشست‌های ورود، از جمله همین مرورگر، بسته می‌شوند.',
    logoutAllUnsupported: 'این قابلیت هنوز روی سرور فعال نیست. تغییر رمز عبور نیز همهٔ نشست‌های دیگر را می‌بندد.',
    sessions: 'نشست‌ها',
  },

  placeholder: {
    title: name => `«${name}» به‌زودی`,
    body: 'این بخش در نسخهٔ بعدی پنل فعال می‌شود.',
    bodyLegacy: 'این بخش در نسخهٔ بعدی پنل فعال می‌شود. اگر همین حالا به آن نیاز دارید، از پنل قدیمی استفاده کنید.',
    openLegacy: 'بازکردن در پنل قدیمی',
    backHome: 'بازگشت به داشبورد',
    // a name, not a sentence: it becomes document.title and the topbar title
    notFoundTitle: 'صفحه پیدا نشد',
    notFoundBody: path => `نشانی «#${path}» در پنل وجود ندارد.`,
  },
};

export default STR;
